added  4 problems of Codewars
afrozchakure/Competitive-Programming-Solutions pull request #30
Opened 2020-11-23 14:54 UTC by soham4abc

Four new problems added of Codewars Platform. More on the way!

2020-11-23 18:18 UTC, afrozchakure requested changes
Thanks for contributing again @soham4abc :tada: .

Remove the extra spaces. It helps others who later refer your code. :smile:

2020-11-23 18:18 UTC, afrozchakure commented on Codewars/Leap_years.cpp
> +
Thanks. Just make sure that your code is formatted correctly, it is considered good practice and makes it easy for others to read your code.
Auto Format option will be available in VS Code and Sublime by default or you could install an extension for .cpp.

2020-11-25 18:10 UTC, afrozchakure commented
@soham4abc do let me know if you are working on it ?

2020-11-26 02:33 UTC, soham4abc commented
Yes I am working on it, I am a bit slow cause of my college assignments ... Sorry for that... Will do it soon.... Plus what kind of formatting do you want?...

2020-11-26 03:13 UTC, soham4abc commented
I have done the changes as per request. Please do see it and let me know it requires more changes or not!

2020-11-26 04:21 UTC, afrozchakure approved these changes

2020-11-26 04:22 UTC, merged

2020-11-26 04:22 UTC, afrozchakure commented
LGTM :tada: :+1: